update Terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -44,7 +44,7 @@ jobs:
       # Plan Terraform
       - name: Terraform Plan
         id: plan
-        if: github.event_name == 'pull_request'
+       # if: github.event_name == 'pull_request'
         run: terraform plan -no-color
       # update pull request
       - uses: actions/github-script@0.9.0
@@ -75,11 +75,11 @@ jobs:
               repo: context.repo.repo,
               body: output
             })
-#      # check the plan status if it fails exit from the job
-#      - name: Terraform Plan Status
-#        id: plan_status
-#        if: steps.plan.outcome == 'failure'
-#        run: exit 1
+      # check the plan status if it fails exit from the job
+      - name: Terraform Plan Status
+        id: plan_status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
       # Apply Terraform in AWS cloud
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
